# Generated by Django 4.1.3 on 2022-11-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.IntegerField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(default='null', max_length=30)),
                ('Address', models.CharField(default='null', max_length=30)),
                ('Balance', models.IntegerField(default='null')),
                ('Phone', models.CharField(default='null', max_length=13)),
            ],
        ),
    ]
