# Generated by Django 4.1.3 on 2022-11-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(db_column='City id', primary_key=True, serialize=False)),
                ('cityname', models.CharField(blank=True, db_column='CityName', max_length=45, null=True, unique=True)),
            ],
        ),
    ]
