# Generated by Django 4.1.2 on 2022-11-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_customercity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCity',
        ),
    ]
